#!/bin/python
import pyaria2, cstr
import argparse, configparser, curses, os, re, sys, time
from socket import gaierror

class Download:
    rows = []
    downloads = []
    num_rows = 0
    num_downloads = 0

    def __init__(self, data):
        self.data = data
        self.gid = self.data['gid']

        self.num_files = len(self.data['files'])

        try:
            self.name = self.data['bittorrent']['info']['name']
        except:
            self.name = os.path.basename(self.data['files'][0]['path'])
        if self.name == '':
            self.name = "N/A"

        self.size = int(self.data['totalLength'])
        self.refresh()

        if self.num_files > 1:
            Download.num_rows += 1 + self.num_files
        else:
            Download.num_rows += 1
        Download.num_downloads += 1

    def refresh(self):
        self.done = int(self.data['completedLength'])
        self.status = self.data['status']

        if self.size != 0:
            self.progress = self.done / self.size * 100
        else:
            self.progress = 0

        self.dl = int(self.data['downloadSpeed']) / 1024

        if self.dl != 0:
            eta_s = (self.size - self.done) / (self.dl * 1024)
            m, s = divmod(eta_s, 60)
            h, m = divmod(m, 60)
            self.eta = "%d:%02d:%02d" % (h, m, s)
        else:
            self.eta = "N/A"

        return self


class Window:
    def __init__(self, height, width, y, x):
        self.height, self.width  = height, width
        self.y, self.x = y, x
        self.win = None

        self.enable_colors = colors.getboolean('colors', True)
        self.progress_markers = ui.get('progress-bar-markers', '[]')
        self.progress_char = ui.get('progress-bar-char', '#')

        self.w_name = self.width - 71
        self.w_size = ui.getint('width-size', 13)
        self.w_status = ui.getint('width-status', 11)
        self.w_progress = ui.getint('width-progress', 15)
        self.w_percent = ui.getint('width-percent', 1)
        self.w_dl = ui.getint('width-dl', 11)
        self.w_eta = ui.getint('width-eta', 10)

        self.option = 0
        self.count = 0
        self.refresh_marker = ui.getfloat('refresh-interval', 0.5) / 0.01
        self.highlight = []

        self.t_string = ""
        self.r_string = ""
        self.s_string = ""

        if self.enable_colors == True:
            self.status_colors = {
                    'active':colors.get('dl-active', 'base3').join('<>'),
                    'paused':colors.get('dl-paused', 'default').join('<>'),
                    'skip':colors.get('dl-skip', 'default').join('<>'),
                    'waiting':colors.get('dl-waiting', 'blue').join('<>'),
                    'pending':colors.get('dl-pending', 'blue').join('<>'),
                    'complete':colors.get('dl-complete', 'green').join('<>'),
                    'removed':colors.get('dl-removed', 'yellow').join('<>'),
                    'error':colors.get('dl-error', 'red').join('<>'),
                    }
        else:
            self.status_colors = {
                    }


    def create(self):
        self.win = curses.newwin(self.height, self.width, self.y, self.x)
        self.win.nodelay(True)
        self.win.keypad(True)
        self.refresh_header()
        self.refresh_status()

    def create_row(self, *items):
        row = ""
        for item in items:
            value = item[0][:(item[1] - item[2])] + ".." if len(item[0]) > item[1] - item[2] else item[0]
            row += (value +  (item[1] - len(value)) * ' ')
        return row

    def refresh_header(self):
        t_name, t_size, t_status, t_progress, t_percent, t_dl, t_eta = "NAME", "SIZE", "STATUS", "PROGRESS", "", "DL", "ETA"

        t_string = self.create_row(
                (t_name, self.w_name, 3),
                (t_size, self.w_size, 3),
                (t_status, self.w_status, 3),
                (t_progress, self.w_progress, 3),
                (t_percent, self.w_percent, 3),
                (t_dl, self.w_dl, 3),
                (t_eta, self.w_eta, 3)
                )

        self.t_string = "<header.b>" + t_string + "</header.b>"

    def refresh_status(self):
        s_server = "server: " + server + ":" + str(port)
        s_string = self.create_row((s_server, self.width - 1, 3))
        self.s_string = "<status.b>" + s_string + "</status.b>"

    def draw(self):
        self.win.clear()
        time.sleep(0.01)
        self.count += 1

        self.highlight = [0] * Download.num_rows
        self.highlight[self.option] = curses.A_REVERSE

        cstr.add(0, 0, self.t_string, self.win, True)

        get_rows(self)
        cstr.add(1, 0, self.r_string, self.win, True)
        # cstr.add(1, 0,
                # self.r_string + "\n[debugging]\ngid: " +
                # Download.rows[self.option]['gid'] + "\nindex: " +
                # str(Download.rows[self.option]['index']) +
                # "\nstatus: " + Download.rows[self.option]['status'],
                # self.win, True)                                             # debugging

        cstr.add(self.height - 1, 0, self.s_string, self.win, True)

        self.win.refresh()


class Keybindings:
    def __init__(self, keybindings):
        self.up = ord(keybindings.get('up', 'k'))
        self.down = ord(keybindings.get('down', 'j'))
        self.pause_all = ord(keybindings.get('pause-all', 'P'))
        self.pause = ord(keybindings.get('pause', 'p'))
        self.add = ord(keybindings.get('add', 'a'))
        self.delete = ord(keybindings.get('delete', 'd'))
        self.purge = ord(keybindings.get('purge', 'D'))
        self.queue_up = ord(keybindings.get('queue-up', 'K'))
        self.queue_down = ord(keybindings.get('queue-down', 'J'))
        self.select = ord(keybindings.get('select-file', 'v'))
        self.quit = ord(keybindings.get('quit', 'q'))


def get_downloads():
    Download.num_rows = 0
    Download.num_downloads = 0
    Download.rows = []
    downloads = []
    active = aria2.tellActive()
    waiting = aria2.tellWaiting(0, 100)
    stopped = aria2.tellStopped(-1, 100)
    states = [active, waiting, stopped]

    for state in states:
        for i in range(len(state)):
            downloads.append(Download(state[i]))

    return downloads


def get_rows(screen):
    screen.r_string = ""

    if Download.num_downloads != 0:
        j = 0
        for i in range(Download.num_downloads):
            if i > screen.height - 3:
                break
            item = Download.downloads[i]

            if screen.progress_markers != '':
                marker_b = screen.progress_markers[0]
                marker_e = screen.progress_markers[1]
                marker_p = 3
            else:
                marker_b = ''
                marker_e = ''
                marker_p = 1

            d_name = item.name
            d_size = str("%0.2f" % (item.size / 1048576)) + " MB"
            d_status = item.status
            d_progress = int((item.progress) / 100 * (screen.w_progress - marker_p)) * screen.progress_char
            d_progress = marker_b + d_progress + (screen.w_progress - len(d_progress) - marker_p) * ' ' + marker_e
            d_percent = str("%0.2f" % item.progress) + "%"
            d_dl = re.sub('^0.0 K', 'N/A', (str("%0.1f" % item.dl) + " K"))
            d_eta = item.eta

            row = screen.create_row(
                    (d_name, screen.w_name, 5),
                    (d_size, screen.w_size, 3),
                    (d_status, screen.w_status, 3),
                    (d_progress, screen.w_progress, 1),
                    (d_percent, screen.w_percent, 3),
                    (d_dl, screen.w_dl, 3),
                    (d_eta, screen.w_eta, 2)
                    )

            color = screen.status_colors.get(d_status, '<default>')

            if screen.highlight[i + j] != 0:
                color = color.replace('>', '.r>')

            screen.r_string += color + row + color.replace('<', '</') + '\n'
            Download.rows.append({'gid':item.gid, 'index':-1, 'status':item.status})

            if item.num_files > 1:
                for k in range(item.num_files):
                    if k == item.num_files - 1:
                        tree_char = "  └─ "
                    else:
                        tree_char = "  ├─ "

                    f_selected = item.data['files'][k]['selected']
                    f_name = tree_char + os.path.basename(item.data['files'][k]['path'])
                    f_size = str("%0.2f" % (int(item.data['files'][k]['length']) / 1048576)) + " MB"

                    if int(item.data['files'][k]['length']) != 0:
                        progress = int(item.data['files'][k]['completedLength']) / int(item.data['files'][k]['length']) * 100
                    else:
                        progress = 0

                    if progress == 100:
                        f_status = 'complete'
                        color = screen.status_colors.get(f_status, '<default>')
                    elif f_selected == 'true':
                        f_status = 'pending'
                    else:
                        f_status = 'skip'

                    if d_status == 'active' or d_status == 'waiting' or d_status == 'complete':
                        color = screen.status_colors.get(f_status, '<default>')
                    color = color.replace('.r', '')

                    f_progress = int((progress / 100) * (screen.w_progress - marker_p)) * screen.progress_char
                    f_progress = marker_b + f_progress + (screen.w_progress - len(f_progress) - marker_p) * ' ' + marker_e
                    f_percent = str("%0.2f" % progress) + "%"

                    f_row = screen.create_row(
                            (f_name, screen.w_name, 5),
                            (f_size, screen.w_size, 3),
                            (f_status, screen.w_status, 3),
                            (f_progress, screen.w_progress, 1),
                            (f_percent, screen.w_percent, 3),
                            )

                    if screen.highlight[i + j + k + 1] != 0:
                        color = color.replace('>', '.r>')

                    screen.r_string += (color + f_row + color.replace('<', '</')) + '\n'
                    Download.rows.append({'gid':item.gid, 'index':k, 'status':item.status})

                j += item.num_files


def key_actions(screen, key):
    if Download.rows != []:
        item = Download.rows[screen.option]

    def refresh_windows():
        tty_h, tty_w = list(map(int, os.popen('stty size', 'r').read().split()))
        screen.height = tty_h
        screen.width = tty_w
        screen.w_name = screen.width - 71
        screen.refresh_header()
        screen.refresh_status()

    def nav_up():
        screen.option = (screen.option - 1) % Download.num_rows

    def nav_down():
        screen.option = (screen.option + 1) % Download.num_rows

    def pause_all():
        if len(aria2.tellActive()) == 0:
            aria2.unpauseAll()
        else:
            aria2.pauseAll()

    def pause():
        if item['status'] == 'active' or item['status'] == 'waiting':
            aria2.pause(item['gid'])
        elif item['status'] == 'paused':
            aria2.unpause(item['gid'])

    def add():
        screen.win.nodelay(False)
        curses.echo(True)
        cstr.add(screen.height - 1, 0, "<status.b>" + "add:" + "</status.b> ", screen.win, True)
        url = screen.win.getstr(screen.height - 1, 5, 200)
        try:
            aria2.addUri([url.strip()])
        except pyaria2.xmlrpc.client.Fault:
            cstr.add(screen.height - 1, 0, "<red>" + "add: " + url.decode('utf-8') + "</red>", screen.win, True)
            screen.win.refresh()
            time.sleep(1)
        curses.echo(False)
        screen.win.nodelay(True)
        screen.win.refresh()

    def delete():
        if screen.option == Download.num_rows - 1:
            screen.option -= 1
        try:
            aria2.remove(item['gid'])
        except:
            aria2.removeDownloadResult(item['gid'])

    def purge():
        aria2.purgeDownloadResult()

    def queue_up():
        if item['status'] == 'waiting':
            aria2.changePosition(item['gid'], -1, 'POS_CUR')
            screen.option -= 1

    def queue_down():
        if item['status'] == 'waiting':
            aria2.changePosition(item['gid'], 1, 'POS_CUR')
            screen.option += 1

    def select():
        if item['index'] != -1:
            aria2.changeOption(item['gid'], {'select-file': str(item['index'] + 1)})

    def quit():
        exit()

    def none():
        pass

    actions = {
            curses.KEY_RESIZE:refresh_windows,
            curses.KEY_UP:nav_up,
            keys.up:nav_up,
            curses.KEY_DOWN:nav_down,
            keys.down:nav_down,
            keys.pause_all:pause_all,
            keys.pause:pause,
            keys.add:add,
            keys.delete:delete,
            keys.purge:purge,
            keys.queue_up:queue_up,
            keys.queue_down:queue_down,
            keys.select:select,
            keys.quit:quit,
            }

    actions.get(key, none)()


def curse(screen):
    tty_h, tty_w = list(map(int, os.popen('stty size', 'r').read().split()))
    screen = Window(tty_h, tty_w, 0, 0)
    screen.create()

    screen.win.clear()
    cstr.init_colors()
    curses.curs_set(False)

    Download.downloads = get_downloads()

    while True:
        if Download.num_rows == 0:
            Download.num_rows = 1

        screen.draw()

        key_in = screen.win.getch()
        key_actions(screen, key_in)

        if key_in != -1:
            screen.count = screen.refresh_marker
            screen.win.refresh()

        if screen.count == screen.refresh_marker:
            Download.downloads = get_downloads()
            screen.count = 0


def exit():
    sys.exit()


def main():
    global aria2, ui, colors, keys, server, port

    config = configparser.ConfigParser()
    config_file = os.path.expanduser("~/.config/narnia/config")

    if not os.path.isfile(config_file):
        import io
        config_file = io.StringIO('[Connection]\n[UI]\n[Colors]\n[Keybindings]')
        config.readfp(config_file)
    else:
        config.read(config_file)

    server = config['Connection'].get('server', 'localhost')
    port = config['Connection'].getint('port', 6800)

    parser = argparse.ArgumentParser(description='Curses-based console client for aria2')
    parser.add_argument('-s','--server', help='Server to connect to', default=server)
    parser.add_argument('-p','--port', help='Port to connect through', default=port)
    parser.add_argument('-a','--add', help='Add URL to download', required=False)

    args = parser.parse_args()
    aria2 = pyaria2.PyAria2(args.server, args.port, None)

    if args.add != None:
        aria2.addUri([args.add])
        sys.exit()

    ui = config['UI']
    colors = config['Colors']
    keys = Keybindings(config['Keybindings'])

    try:
        curses.wrapper(curse)
    except gaierror:
        print("Invalid server:", server)
    except ConnectionRefusedError:
        print("Connection refused.\nMake sure aria2 is running or authorized on", server + ":" + str(port))


main()
